import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../components/header'
import Main from '../components/main'
import Footer from '../components/footer'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@700&display=swap" rel="stylesheet"></link>
        <script async src="https://kit.fontawesome.com/4e203ce1b2.js" crossorigin="anonymous"></script>
      </Head>
      
      <main className={styles.main}>
        <div class="container">
              <Header/>
              <Main/>
        </div>

        <div id={styles.assignments_cont}>
          <div class="container">
            <div class={styles.inner_cont}>
                <p id={styles.title}>Open for assignments</p>
                <p id={styles.desc}>Interested in commissioning me an art project? I am currently available for assignments worldwide.</p>
                <a href="#" class="page_btn">
                    Get in touch
                </a>
            </div>
              
            
          </div>
        </div>

        <div class="container">
            <Footer/>

        </div>
      </main>
    </>
  )
}
